In [82]:
import  numpy as np

In [83]:
world_alcohol = numpy.genfromtxt('world_alcohol.txt', delimiter=',', dtype=str, skip_header=1)
print(type(world_alcohol))
world_alcohol

<class 'numpy.ndarray'>


array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1987', 'Africa', 'Malawi', 'Other', '0.75'],
       ['1989', 'Americas', 'Bahamas', 'Wine', '1.5'],
       ['1985', 'Africa', 'Malawi', 'Spirits', '0.31']], dtype='<U52')

In [43]:
# vector or matrix

vector = numpy.array([5,10,15,20])
matrix1 = numpy.array([[5,10],[10,20]])
print(vector)
print(matrix1)
print(vector.shape)
print(matrix1.shape)

[ 5 10 15 20]
[[ 5 10]
 [10 20]]
(4,)
(2, 2)


In [31]:
matrix2 = numpy.array([[1,2],[3,'4']])
print(matrix2.dtype)

<U21


In [39]:
# select element

world_alcohol[1,0:2]

array(['1986', 'Americas'], dtype='<U52')

In [49]:
# compare

result = (matrix1 == 10)
print(result)
print(matrix1[result])


matrix3 = numpy.array(
    [[5,10,15],
    [20,25,30],
    [35,40,45]]
)
second_column = (matrix3[:,1]==25)
print(second_column)
print(matrix3[:,second_column])

[[False  True]
 [ True False]]
[10 10]
[False  True False]
[[10]
 [25]
 [40]]


In [60]:
# min max
print(matrix3.min())
print(matrix3.max())
print(matrix3.sum(axis=1)) #sum by row

5
45
[ 30  75 120]


In [55]:
# transform

vector2 = numpy.array(['1','2','3'])
print(vector2.dtype)
vector2 = vector2.astype(float)
print(vector2.dtype)
print(vector2)

<U1
float64
[1. 2. 3.]


In [75]:
# reshape

print(numpy.arange(15))
a = numpy.arange(15).reshape(3,5)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype.name)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
(3, 5)
15
int64


In [89]:
# initialize

print( np.zeros((3,4)) )
print( np.ones((2,3,4), dtype=np.int32) )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [99]:
# random

print(np.random.random((2,3)))

from numpy import pi
print(np.linspace(0,2*pi,100))

[[0.66162558 0.62833146 0.91027258]
 [0.58935784 0.61473036 0.72134275]]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.

In [106]:
# multiplication, dot

A = np.array([
    [1,1],
    [0,1]
])
B= np.array([
    [2,0],
    [3,4]
])
print(A*B)
print(A.dot(B))
print(np.dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[2 2]
 [3 7]]
[[5 4]
 [3 4]]


In [116]:
# operation

a = np.floor(10*np.random.random((3,4)))
print(a)

print(a.ravel())

print(a.reshape(2,-1)) # -1 means default value

print(a.T)
      

[[6. 6. 3. 9.]
 [9. 4. 4. 3.]
 [5. 8. 5. 0.]]
[6. 6. 3. 9. 9. 4. 4. 3. 5. 8. 5. 0.]
[[6. 6. 3. 9. 9. 4.]
 [4. 3. 5. 8. 5. 0.]]
[[6. 9. 5.]
 [6. 4. 8.]
 [3. 4. 5.]
 [9. 3. 0.]]


In [122]:
# stack

a = np.floor(10*np.random.random((3,4)))
b = np.floor(10*np.random.random((3,4)))

print(a)
print(b)

print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[6. 2. 3. 2.]
 [6. 4. 2. 6.]
 [3. 4. 2. 1.]]
[[2. 7. 3. 0.]
 [4. 0. 4. 2.]
 [0. 2. 1. 4.]]
[[6. 2. 3. 2. 2. 7. 3. 0.]
 [6. 4. 2. 6. 4. 0. 4. 2.]
 [3. 4. 2. 1. 0. 2. 1. 4.]]
[[6. 2. 3. 2.]
 [6. 4. 2. 6.]
 [3. 4. 2. 1.]
 [2. 7. 3. 0.]
 [4. 0. 4. 2.]
 [0. 2. 1. 4.]]


In [128]:
# split

a = np.floor(10*np.random.random((2,12)))
print(a)
print( np.vsplit(a,2) )
print( np.hsplit(a,4) )
print( np.hsplit(a,(3,4)) )

[[5. 3. 5. 1. 1. 5. 7. 8. 9. 3. 0. 6.]
 [8. 7. 8. 9. 3. 0. 7. 0. 3. 0. 4. 4.]]
[array([[5., 3., 5., 1., 1., 5., 7., 8., 9., 3., 0., 6.]]), array([[8., 7., 8., 9., 3., 0., 7., 0., 3., 0., 4., 4.]])]
[array([[5., 3., 5.],
       [8., 7., 8.]]), array([[1., 1., 5.],
       [9., 3., 0.]]), array([[7., 8., 9.],
       [7., 0., 3.]]), array([[3., 0., 6.],
       [0., 4., 4.]])]
[array([[5., 3., 5.],
       [8., 7., 8.]]), array([[1.],
       [9.]]), array([[1., 5., 7., 8., 9., 3., 0., 6.],
       [3., 0., 7., 0., 3., 0., 4., 4.]])]


In [140]:
# assignment

a = np.arange(12)
b = a
b.shape = (3,4)
print(a)
print(b)
print(id(a))
print(id(b))
print(a is b)
print('-'*20)

c = a.view() # different id but same value
print(c is a)
c.shape = 2,6
print(a)
print(id(a))
print(id(c))
c[1,1] = 555
print(a)
print('-'*20)

d = a.copy() # totally different
print(d is a)
print(id(a))
print(id(d))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
140342804717360
140342804717360
True
--------------------
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
140342804717360
140342804787488
[[  0   1   2   3]
 [  4   5   6 555]
 [  8   9  10  11]]
--------------------
False
140342804717360
140342804787408


In [157]:
# argmax

data = np.sin(np.arange(20)).reshape(5,4)
print(data)
ind = data.argmax(axis=0) # maximum value for each column
print(ind)

data_max = data[ind, range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [159]:
# tile

a = np.arange(0,40,10)
print(a)
b = np.tile(a,(3,5))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [165]:
# sort, argsort

a = np.array([
    [4,3,5,],
    [1,2,1]
])
print(a)
b= np.sort(a,axis=1) # sort by row
print(b)
print('-'*20)

a = np.array([4,3,1,2])
j = np.argsort(a) # index from smallest number
print(j)
print(a[j])

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
--------------------
[2 3 1 0]
[1 2 3 4]
